<?php

/**
 * @file
 * GDPR onetrust module.
 */

/**
 * Defining constants for REGEX and Onetrust Domain.
 */
const GDPR_ONETRUST_UUID_REGEX = '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(-test){0,1}$/i';
const GDPR_ONETRUST_LIVE_DOMAIN = '//cdn.cookielaw.org/consent/';
const GDPR_ONETRUST_STAGE_DOMAIN = 'https://optanon.blob.core.windows.net/consent/';

/**
 * Hook__preprocess_page to load the library.
 */
function gdpr_onetrust_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'gdpr_onetrust/gdpr-onetrust-api';
}

/**
 * Hook__page_attachments to load inline JS.
 */
function gdpr_onetrust_page_attachments(array &$attachments) {
  $languages = \Drupal::languageManager()->getLanguages();
  $gdpr_config = \Drupal::config('gdpr_onetrust.settings');
  $current_language_id = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (count($languages) == 1 && !is_null($gdpr_config->get('gdpr_onetrust_compliance_uuid'))) {
    $api_key = $gdpr_config->get('gdpr_onetrust_compliance_uuid');
  }
  else {
    $api_key = $gdpr_config->get('gdpr_onetrust_compliance_uuid_' . $current_language_id);
  }
  if (!empty($api_key)) {

    $ret = preg_match(GDPR_ONETRUST_UUID_REGEX, $api_key, $matches);
    $domain = (isset($matches[1]) && $matches[1] == '-test') ? GDPR_ONETRUST_STAGE_DOMAIN : GDPR_ONETRUST_LIVE_DOMAIN;
    $cdn_url = $domain . $api_key . '.js';
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => '',
        '#attributes' => ['src' => $cdn_url],
      ],
      'onetrust_inline_cdn',
    ];
  }
}
